### ISSUE TITLE
Fix firefox context menu multi-element css oddities

### ISSUE THREAD

**Issue by KeniMorri** [mozilla/brackets#199]
Presently within firefox whenever 2 items reside on the same line in a context menu, the second element is pushed to the second line, and rendered far to the right as seen below:

| File Options | Project Manager | Color picker |
| --- | --- | --- |
| ![screenshot 2015-04-14 16 25 55](https://cloud.githubusercontent.com/assets/1750230/7146686/622a6626-e2c3-11e4-92a4-439a5bdb6c43.png) | ![screenshot 2015-04-14 16 25 11](https://cloud.githubusercontent.com/assets/1750230/7146689/6817bc0a-e2c3-11e4-9995-959462f7af41.png) | ![screenshot 2015-04-14 16 25 46](https://cloud.githubusercontent.com/assets/1750230/7146692/6bf71d3e-e2c3-11e4-870a-8bc18f012b26.png) |

**Comment by JordanTheriault** [comment]
Related to [bug id488725](https://bugzilla.mozilla.org/show_bug.cgi?id=488725) in Firefox. Trying to locate an effective CSS fix for this issue.

**Comment by humphd** [comment]
I'm going to move this out of the current heartbeat, it's not critical to this release.

**Comment by JordanTheriault** [comment]
Everything except colour picker fixed in #295

**Comment by JordanTheriault** [comment]
#295 is now merged, and all that remains is to fix the colour picker.

**Comment by humphd** [comment]
This is still an issue, and is almost worse than before:

![screenshot 2015-07-22 10 11 25](https://cloud.githubusercontent.com/assets/427398/8827353/409a9352-305a-11e5-9913-02339934391f.png)

**Comment by humphd** [comment]
@flukeout, this one I have no idea how to fix, and it would be nice if we worked in Firefox.  Do you have time to debug?

**Comment by humphd** [comment]
I'm going to move this out of the Thimble MVP.  This needs a CSS wizard to cast a spell on it, and that isn't me.

**Comment by flukeout** [comment]
Confirmed that it's still an issue, will close and refile.
